version: '3.8'
name: icog-psql-container
services:
  db:
    container_name: pgvector_container
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 2214
      POSTGRES_DB: icog_db
    ports:
      - "5432:5432"
    volumes:
      - ./database-init/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: icog_api
    env_file: .env
    environment:
      PORT: 8080
    volumes:
      - .:/app
    ports:
      - 8080:8080
