"""Adding cloned_document field to bookmark

Revision ID: 25f8ddced8ac
Revises: e2509c7b50b4
Create Date: 2024-03-22 11:14:04.964608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '25f8ddced8ac'
down_revision: Union[str, None] = 'e2509c7b50b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('cloned_documents', sa.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark', 'cloned_documents')
    # ### end Alembic commands ###
