"""Allow doc title to be null

Revision ID: 4846a5f4c2e5
Revises: d22580b5ac75
Create Date: 2024-03-19 17:09:10.462998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '4846a5f4c2e5'
down_revision: Union[str, None] = 'd22580b5ac75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('document', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('document', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
