"""Rename articleIsAbout to is_about in Document

Revision ID: 7a09c59166e1
Revises: 7aad41bf24a1
Create Date: 2024-04-05 17:27:55.758506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '7a09c59166e1'
down_revision: Union[str, None] = '7aad41bf24a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('is_about', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('document', 'articleIsAbout')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('articleIsAbout', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('document', 'is_about')
    # ### end Alembic commands ###
