"""Adding articleIsAbout to Document

Revision ID: 7aad41bf24a1
Revises: 75003faa267e
Create Date: 2024-04-05 17:15:21.815049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '7aad41bf24a1'
down_revision: Union[str, None] = '75003faa267e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('articleIsAbout', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'articleIsAbout')
    # ### end Alembic commands ###
