"""Adding LLM usage to Document

Revision ID: cd45169659d6
Revises: 4846a5f4c2e5
Create Date: 2024-03-21 23:06:02.395253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'cd45169659d6'
down_revision: Union[str, None] = '4846a5f4c2e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('llm_usage', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'llm_usage')
    # ### end Alembic commands ###
