"""Add llm_service_meta jsonb to Document

Revision ID: dfc1874349bf
Revises: d7e5377df0eb
Create Date: 2024-03-23 11:51:46.128542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfc1874349bf'
down_revision: Union[str, None] = 'd7e5377df0eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('llm_service_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('document', 'llm_usage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('llm_usage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('document', 'llm_service_meta')
    # ### end Alembic commands ###
