"""init

Revision ID: 053941ff6d25
Revises: 
Create Date: 2023-08-20 11:37:14.172387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '053941ff6d25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('update_at', sa.DateTime(), nullable=False),
                    sa.Column('document_id', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('document',
                    sa.Column('authors', sa.ARRAY(sa.Float()), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('summary_generated',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('publication_date',
                              sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('keyphrase',
                    sa.Column('word_vec', pgvector.sqlalchemy.Vector(
                        dim=384), nullable=True),
                    sa.Column('context_vec', pgvector.sqlalchemy.Vector(
                        dim=384), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'word', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('start', sa.Integer(), nullable=True),
                    sa.Column('end', sa.Integer(), nullable=True),
                    sa.Column('score', sa.Float(), nullable=True),
                    sa.Column(
                        'type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('entity_group',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'context', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('document_id', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('wd_alias',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('lcase_alias', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('wd_item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('wikipedia_page_id',
                              sa.Integer(), nullable=True),
                    sa.Column('views', sa.Integer(), nullable=True),
                    sa.Column('links', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wd_item')
    op.drop_table('wd_alias')
    op.drop_table('keyphrase')
    op.drop_table('document')
    op.drop_table('bookmark')
    # ### end Alembic commands ###
