"""Adding user_id to bookmarks

Revision ID: 0aa871055675
Revises: 49929ad05680
Create Date: 2023-09-06 07:58:34.944030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '0aa871055675'
down_revision: Union[str, None] = '49929ad05680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark', 'user_id')
    # ### end Alembic commands ###
