"""Document model- Remove bookmark Id and adding original text

Revision ID: 168d627f9dfb
Revises: edf49b75908e
Create Date: 2023-10-02 08:22:29.902095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '168d627f9dfb'
down_revision: Union[str, None] = 'edf49b75908e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('original_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'original_text')
    # ### end Alembic commands ###
