"""remove wikidata and keyphrase table

Revision ID: 1ecee2e06ec1
Revises: 168d627f9dfb
Create Date: 2024-01-05 08:56:10.861757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ecee2e06ec1'
down_revision: Union[str, None] = '168d627f9dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('name_description_vec', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wikidata_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('document', sa.Column('summary_bullet_points_json', sa.JSON(), nullable=True))
    op.add_column('document', sa.Column('short_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('document', sa.Column('raw_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('document', 'summary_bullet_points')
    op.drop_column('document', 'spacy_entities_json')
    op.drop_column('document', 'summary_generated')
    op.drop_column('document', 'concepts_generated')
    op.drop_column('document', 'llama2_entities_raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('llama2_entities_raw', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('concepts_generated', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('summary_generated', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('spacy_entities_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('summary_bullet_points', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('document', 'raw_answer')
    op.drop_column('document', 'short_summary')
    op.drop_column('document', 'summary_bullet_points_json')
    op.drop_table('entity')
    # ### end Alembic commands ###
