"""Making Entity and Concept fields nullable

Revision ID: 434cfc45b34c
Revises: 8d843d9a1ad0
Create Date: 2023-10-11 16:14:14.112985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '434cfc45b34c'
down_revision: Union[str, None] = '8d843d9a1ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('concept', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entity', 'wikidata_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entity', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entity', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entity', 'wikidata_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('concept', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
