"""Adding refs tables

Revision ID: 448bb7a4c887
Revises: 434cfc45b34c
Create Date: 2023-10-17 09:06:53.998542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '448bb7a4c887'
down_revision: Union[str, None] = '434cfc45b34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept',
    sa.Column('concept_vector', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.Column('description_vector', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.Column('history_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conceptdoc',
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('concept_id', 'document_id')
    )
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wikidata_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entitytdoc',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('entity_id', 'document_id')
    )
    op.create_table('tldr',
    sa.Column('description_vector', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tldrdoc',
    sa.Column('tldr_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tldr_id', 'document_id')
    )
    op.drop_column('keyphrase', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyphrase', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('tldrdoc')
    op.drop_table('tldr')
    op.drop_table('entitytdoc')
    op.drop_table('entity')
    op.drop_table('conceptdoc')
    op.drop_table('concept')
    # ### end Alembic commands ###
