"""Adding bullet points and entities fields to Documents

Revision ID: 49929ad05680
Revises: 524862cfdd9f
Create Date: 2023-09-05 08:22:32.707440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '49929ad05680'
down_revision: Union[str, None] = '524862cfdd9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('summary_bullet_points', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('document', sa.Column('found_entities_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('document', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('document', 'found_entities_raw')
    op.drop_column('document', 'summary_bullet_points')
    # ### end Alembic commands ###
