"""Change word vec and context vec fields in Keyphrases to allow none

Revision ID: 524862cfdd9f
Revises: c8d0e0b0d608
Create Date: 2023-08-23 08:27:39.497729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '524862cfdd9f'
down_revision: Union[str, None] = 'c8d0e0b0d608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
