"""Concert spacy column to JSON

Revision ID: 677f1c683044
Revises: d2988d0bf2b3
Create Date: 2023-09-22 11:09:04.438685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '677f1c683044'
down_revision: Union[str, None] = 'd2988d0bf2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('spacy_entities_json', sa.JSON(), nullable=True))
    op.drop_column('document', 'spacy_entities_raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('spacy_entities_raw', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('document', 'spacy_entities_json')
    # ### end Alembic commands ###
