"""Adding bookmark_id to Document

Revision ID: 68f481d4558d
Revises: 7457dc289637
Create Date: 2023-09-08 16:26:05.110983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '68f481d4558d'
down_revision: Union[str, None] = '7457dc289637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('bookmark_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'bookmark_id')
    # ### end Alembic commands ###
