"""Adding concept table

Revision ID: 70637a1027f0
Revises: 1ecee2e06ec1
Create Date: 2024-01-05 09:09:10.537181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70637a1027f0'
down_revision: Union[str, None] = '1ecee2e06ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept',
    sa.Column('name_description_vec', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('document', sa.Column('summary_bullet_points', sa.JSON(), nullable=True))
    op.drop_column('document', 'summary_bullet_points_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('summary_bullet_points_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('document', 'summary_bullet_points')
    op.drop_table('concept')
    # ### end Alembic commands ###
