"""Add column type to Entity

Revision ID: 843b21e085be
Revises: 0ef4645ca76f
Create Date: 2024-01-06 17:02:39.767312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '843b21e085be'
down_revision: Union[str, None] = '0ef4645ca76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity', 'type')
    # ### end Alembic commands ###
