"""Adding spacy entities to Document table

Revision ID: b679e7c3b2bd
Revises: d82ce344113e
Create Date: 2023-09-20 08:05:17.720937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'b679e7c3b2bd'
down_revision: Union[str, None] = 'd82ce344113e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
