"""Making Entity and Concept fields nullable true

Revision ID: d22580b5ac75
Revises: 4a41f5758487
Create Date: 2024-02-17 10:31:23.208582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'd22580b5ac75'
down_revision: Union[str, None] = '4a41f5758487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('concept', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('concept', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entity', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entity', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entity', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entity', 'wikidata_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entity', 'wikidata_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entity', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entity', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entity', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('concept', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('concept', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
