"""Adding Concepts field to Document table

Revision ID: d2988d0bf2b3
Revises: b679e7c3b2bd
Create Date: 2023-09-22 08:12:06.779985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'd2988d0bf2b3'
down_revision: Union[str, None] = 'b679e7c3b2bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('concepts_generated', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('document', sa.Column('llama2_entities_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('document', sa.Column('spacy_entities_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('document', 'found_entities_raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('found_entities_raw', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('document', 'spacy_entities_raw')
    op.drop_column('document', 'llama2_entities_raw')
    op.drop_column('document', 'concepts_generated')
    # ### end Alembic commands ###
