"""Deploy to STG March 23rd

Revision ID: 555bc609c473
Revises: 704d8e72895f
Create Date: 2024-03-23 13:16:07.920153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '555bc609c473'
down_revision: Union[str, None] = '704d8e72895f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('cloned_documents', sa.ARRAY(sa.Integer()), nullable=True))
    op.alter_column('bookmark', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.add_column('document', sa.Column('llm_service_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('document', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('document', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('document', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('document', 'llm_service_meta')
    op.alter_column('bookmark', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               nullable=True)
    op.drop_column('bookmark', 'cloned_documents')
    # ### end Alembic commands ###
